# Generated by Django 3.1.3 on 2020-12-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('mastered_level', models.IntegerField(default=0)),
                ('difficulty', models.CharField(max_length=3)),
            ],
        ),
    ]
