# Generated by Django 3.1.4 on 2020-12-08 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201208_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makeroute',
            name='route',
        ),
    ]
